export const UPDATE_CART = "UPDATE_CART";
export const TOGGLE_CHECKOUT_DRAWER = "TOGGLE_CHECKOUT_DRAWER";

export const UPDATE_SHIPPING_FORM = "UPDATE_SHIPPING_FORM";
export const UPDATE_BILLING_FORM = "UPDATE_BILLING_FORM";
