export const UPDATE_CART = "UPDATE_CART";
export const TOGGLE_CHECKOUT_DRAWER = "TOGGLE_CHECKOUT_DRAWER";

export const UPDATE_SHIPPING_FORM = "UPDATE_SHIPPING_FORM";
export const UPDATE_BILLING_FORM = "UPDATE_BILLING_FORM";

export const SET_CHECKOUT_INDEX = "SET_CHECKOUT_INDEX";
export const UPDATE_CHECKOUT_MAX_INDEX = "UPDATE_CHECKOUT_MAX_INDEX";
export const SET_CHECKOUT_SUCCESSFUL = "SET_CHECKOUT_SUCCESSFUL";
export const CLEAR_CART = "CLEAR_CART";
